language: python
cache: pip
dist: xenial
install: pip install tox

matrix:
  include:
jobs:
  include:
    - stage: test
      python: 2.7
      env: TOX_ENV=django18-py27
    - stage: test
      python: 3.4
      env: TOX_ENV=django18-py34
    - stage: test
      python: 3.5
      env: TOX_ENV=django18-py35
    - stage: test
      python: 2.7
      env: TOX_ENV=django19-py27
    - stage: test
      python: 3.4
      env: TOX_ENV=django19-py34
    - stage: test
      python: 3.5
      env: TOX_ENV=django19-py35
    - stage: test
      python: 2.7
      env: TOX_ENV=django110-py27
    - stage: test
      python: 3.5
      env: TOX_ENV=django110-py35
    - stage: test
      python: 2.7
      env: TOX_ENV=django111-py27
    - stage: test
      python: 3.5
      env: TOX_ENV=django111-py35
    - stage: test
      python: 3.6
      env: TOX_ENV=django111-py36
    - stage: test
      python: 3.4
      env: TOX_ENV=django20-py34
    - stage: test
      python: 3.5
      env: TOX_ENV=django20-py35
    - stage: test
      python: 3.6
      env: TOX_ENV=django20-py36
    - stage: test
      python: 3.7
      env: TOX_ENV=django20-py37
    - stage: test
      python: 3.5
      env: TOX_ENV=django21-py35
    - stage: test
      python: 3.6
      env: TOX_ENV=django21-py36
    - stage: test
      python: 3.7
      env: TOX_ENV=django21-py37
    - stage: test
      python: 3.6
      env: TOX_ENV=django22-py36
    - stage: test
      python: 3.7
      env: TOX_ENV=django22-py37
    - stage: lint
      script: echo TODO
    # - stage: coverage
    # install: pip install tox coveralls
    # script: tox -e $TOX_ENV
    # after_success: [ "$TOX_ENV" = "coveralls-django21-py37" ] && coveralls || true
script: tox -e $TOX_ENV

stages:
  - test
  - lint

branches:
  only:
    - master
notifications:
  email: false
